name: edm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.8
  - cudatoolkit=11.6.0
  - dav1d=1.2.1
  - expat=2.7.1
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - imageio=2.37.0
  - intel-openmp=2023.0.0
  - jpeg=9f
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libavif=1.1.1
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lightning=2.1.4
  - lightning-utilities=0.15.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.5
  - numpy=2.0.2
  - numpy-base=2.0.2
  - openjpeg=2.5.2
  - openssl=3.0.18
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - psutil=7.0.0
  - pthread-stubs=0.3
  - pybind11-abi=4
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.9.23
  - python_abi=3.9
  - pytorch-lightning=2.1.4
  - pytorch-mutex=1.0
  - readline=8.3
  - requests=2.32.5
  - scipy=1.13.1
  - setuptools=72.1.0
  - sqlite=3.50.2
  - tbb=2021.8.0
  - tk=8.6.15
  - torchmetrics=1.5.2
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - args==0.1.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==15.1.0
      - braceexpand==0.1.7
      - clint==0.5.1
      - clip==1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - diffusers==0.35.1
      - dill==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - fairscale==0.4.13
      - filelock==3.19.1
      - fire==0.7.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - h11==0.16.0
      - hf-xet==1.1.10
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.2.1
      - ninja==1.13.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - piq==0.8.0
      - pluggy==1.6.0
      - propcache==0.4.1
      - protobuf==3.20.3
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyspng==0.1.3
      - pytest==7.2.0
      - pytest-split==0.8.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.14
      - regex==2025.9.1
      - rich==14.2.0
      - safetensors==0.6.2
      - sentencepiece==0.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - termcolor==3.1.0
      - timm==1.0.19
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.8.0
      - torchvision==0.23.0
      - transformers==4.57.1
      - triton==3.4.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - wcwidth==0.2.14
      - webdataset==0.2.100
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /work/hdd/becj/zli42/zli42_envs/edm
